services:
  - type: web
    name: caudo-backend
    runtime: node
    plan: free
    region: oregon
    rootDir: backend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start:prod
    healthCheckPath: /api/docs
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: NODE_ENV
        value: production
      - key: DB_HOST
        value: aws-0-us-west-2.pooler.supabase.com
      - key: DB_PORT
        value: "6543"
      - key: DB_USERNAME
        value: postgres.dxzixbndgilwnqffemzx
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        value: postgres
      - key: DB_SSL
        value: "true"
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRATION
        value: 24h
      - key: UPLOAD_PATH
        value: ./uploads
      - key: MAX_FILE_SIZE
        value: "5242880"
      - key: APP_URL
        value: https://caudo-backend.onrender.com
      - key: CORS_ORIGINS
        value: https://caudo-frontend.onrender.com,http://localhost:4200

  - type: web
    name: caudo-frontend
    runtime: node
    plan: free
    region: oregon
    rootDir: frontend
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run serve:ssr:CaudoFront
    envVars:
      - key: NODE_VERSION
        value: 22.12.0
      - key: NODE_ENV
        value: production
